repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args:
          - --max-line-length=79
          - --max-doc-length=72
          - --ignore=E203,W503
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 9feadeb
    hooks:
      - id: mypy
        exclude: ^tests/
        args:
          - --disallow-untyped-defs
          - --check-untyped-defs
          - --warn-redundant-casts
          - --no-implicit-optional
          - --strict-optional
  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
      - id: black
