version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    ports:
      - '${APP_PORT}:8000'

    volumes:
      - .:/var
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.9
    volumes:
      - .:/var/lib/postgresql/data_app
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
