version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    image: 'web'
    entrypoint: /code/entrypoint_web.sh
    ports:
      - '8000:8000'

    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13.9
    volumes:
      - .:/var/lib/postgresql/data_app
    env_file:
      - .env
    ports:
      - '5432:5432'
