version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    image: 'core_app'
    command:  gunicorn trade_processor.wsgi:application --bind 0.0.0.0:8000
    ports:
      - '8000:8000'


    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres:13.9
    volumes:
      - .:/var/lib/postgresql/data_app
    env_file:
      - ./.env


volumes:
  postgres_data:
