version: '3.8'

services:
  web:
    restart: unless-stopped
    build:
      dockerfile: ./Dockerfile
    image: 'web'


    entrypoint: /code/entrypoint_web.sh
    ports:
      - '${APP_PORT}:8000'

    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
  celery:
    restart: unless-stopped
    image: "web"
    entrypoint: /code/entrypoint_celery.sh
    volumes:
      - .:/code
    env_file:
      - ./.env
    depends_on:
      - web
      - redis
      - db

  redis:
    image: redis:alpine
    command:  redis-server --port ${REDIS_PORT}

    ports:
      - "${REDIS_PORT}:7777"

  db:
    image: postgres:13.9
    volumes:
      - .:/var/lib/postgresql/data_app
    env_file:
      - .env
    ports:
      - '${POSTGRES_PORT}:5432'
