# Generated by Django 4.2.2 on 2023-06-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="name",
            field=models.CharField(default=None, max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="asset",
            name="type",
            field=models.CharField(
                choices=[("Cryptocurrency", "Cryptocurrency"), ("Share", "Share")],
                default=None,
                max_length=14,
            ),
        ),
    ]
