# Generated by Django 4.2.3 on 2023-07-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                check=models.Q(("current_price__gte", 0)),
                name="check_current_price_is_positive",
            ),
        ),
    ]
