# Generated by Django 4.2.2 on 2023-06-22 07:34

import django.db.models.deletion
from django.db import migrations, models

# mypy: ignore-errors


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("assets", "0001_initial"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "initializer",
                    models.CharField(
                        choices=[("Auto", "Auto"), ("Manual", "Manual")],
                        default="Manual",
                        max_length=6,
                    ),
                ),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("Sell", "Sell"), ("Buy", "Buy")],
                        max_length=4,
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("quantity", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Finished", "Finished"),
                            ("Cancelled", "Cancelled"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="accounts.portfolio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AutoOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation_type",
                    models.CharField(
                        choices=[("Sell", "Sell"), ("Buy", "Buy")],
                        max_length=4,
                    ),
                ),
                (
                    "desired_price",
                    models.DecimalField(decimal_places=2, max_digits=11),
                ),
                ("quantity", models.IntegerField()),
                (
                    "price_direction",
                    models.CharField(
                        choices=[("Higher", "Higher"), ("Lower", "Lower")],
                        max_length=6,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Finished", "Finished"),
                            ("Cancelled", "Cancelled"),
                            ("Opened", "Opened"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assets.asset",
                    ),
                ),
                (
                    "portfolio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="auto_orders",
                        to="accounts.portfolio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
