# Generated by Django 4.2.3 on 2023-07-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="autoorder",
            constraint=models.CheckConstraint(
                check=models.Q(("desired_price__gte", 0)),
                name="check_desired_price_is_positive",
            ),
        ),
    ]
