# Generated by Django 4.2.3 on 2023-07-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_autoorder_check_desired_price_is_positive"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                check=models.Q(("price__gte", 0)),
                name="check_price_is_positive"
            ),
        ),
    ]
