# Generated by Django 4.2.2 on 2023-06-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_order_options_alter_autoorder_operation_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Finished", "Finished"), ("Cancelled", "Cancelled")],
                default="Finished",
                max_length=9,
            ),
        ),
    ]
