# Generated by Django 4.2.3 on 2023-07-05 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_order_check_price_is_positive"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autoorder",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
