# Generated by Django 4.2.3 on 2023-07-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("relevance_value__gte", 0)),
                name="check_relevance_value_is_positive",
            ),
        ),
    ]
