# Generated by Django 4.2.3 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recommendations",
         "0002_recommendation_check_relevance_value_is_positive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="recommendation",
            name="check_relevance_value_is_positive",
        ),
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("relevance_value__lte", 1.0)),
                name="check_relevance_value_is_lte_one",
            ),
        ),
    ]
