# Generated by Django 4.2.3 on 2023-07-05 14:02

from django.db import migrations, models

# mypy: ignore-errors


class Migration(migrations.Migration):
    dependencies = [
        (
            "recommendations",
            "0003_remove_recommendation_check"
            "_relevance_value_is_positive_and_more",
        ),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="recommendation",
            constraint=models.CheckConstraint(
                check=models.Q(("relevance_value__gte", 0)),
                name="check_relevance_value_is_positive",
            ),
        ),
    ]
