name: hooks

on:
  push:
    branches: 
      - feature/**
      - main
      - dev
      - fix/**
  pull_request:
    branches: 
      - dev

jobs:
  Lint:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10
      - name: Install pipenv
        run: pip install pipenv
      - name: Run install requirements
        run: |
          pipenv install --dev
      - name: run-pre-commit
        working-directory: ./trade_processor
        run: |
            pipenv run pre-commit run --all-files
