name: hooks

on:
  push:
    branches: 
      - features/**
      - main
      - dev
      - fix/**
  pull_request:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Python, pipenv and Pipfile packages
        uses: palewire/install-python-pipenv-pipfile@v3
        with:
          # The version of Python to use
          python-version: 3.10
      - name: run-pre-commit
        uses: samwlms/simple-pre-commit@1.3
